### ISSUE TITLE
Package manager: Discussion

### ISSUE THREAD

**Issue by HKalbasi** [openscad/openscad#3479]
There were tries to implement a package manager, Or something with same goals (#2377, #2384, #3124, #1913, ...) But they were left without result. I open this issue for a place to solution-neutral discussion and as a tracking issue for package manager feature.

# Goals
1. **Isolated libraries**: Every project needs its own libraries, and two projects may depend on different versions of library. Or there maybe similar version issues between two dependencies that have a common nested dependency.
2. **Discoverability**:  A central registry provides an easy place to look for existing packages. Currently it is a "library" part in the website, but it has very limited features and is unscalable. A package manager, combined with tagging, makes it possible for a registry to provide ecosystem-wide information, such as a list of the most popular or most-depended-on packages.
3. **Micro libraries**: Package manager will make it easy to reuse parts between multiple projects, without copy pasting files and loss of sync. It also makes possible to publish micro libraries for other peoples. Currently, libraries are enormous and general and this means we should repeat ourselves and other people for specialized works.

# Solutions
* **A simple package manager**: Something similar to node `npm`, ruby `gem`, rust `cargo`, ... For example, `scadpm`
  * Pros
    * Simple, battle proven solution.
  * Cons
    * Huge development cost.
    * Hosting cost of a service
* **An alternative module path resolve method**: An alternative to global library folder, for each project. Something like `node_modules`. Solves 1 and 3 and opens a door for future developments.
  * Cons
    * It destroys the way back. With this implemented, Some of other options will be infeasible, And solution for 2 maybe missed.
* **Use a ready package manager**: Current package managers are agnostic to what is stored into them. For example, We can use `npm` as openscad package manager, which is the case for many scripting languages (though, most of them are closely related to js).
  * Pros
     * Little development cost
  * Cons
     * It destroys openscad independence.
* **Http import and use**: Add support for some statement like `include<https://github.com/xyz/abc/folderA/fileB>`
  * Pros
    * Little development cost
    * Very close to current state, It is a small, backward compatible change, relative to others.
  * Cons
    * Web pages die sooner or later. Hard coding urls into source files and repeating them many times is not a good idea, Specially for changing them. A package manager can install packages from urls, and keep other useful metadata like content-hash, so in source files we can only mention the name of packages which is cleaner.
    * Goal 2 remains unsolved.

I'm not native English speaker, Sorry for my English errors and please fix them. And Add more (Or tell me to Add) solutions and goals if I missed them.

**Comment by alexose** [comment]
A package manager would be a hugely important milestone for OpenSCAD.  I put $50 towards the bounty on this one.

Working package management would unlock a more cohesive development experience.  It would encourage developers to publish good APIs and help bubble the most useful libraries to the top.  Solutions to common problems would become standardized, and more functional-style programming would emerge.

As an OpenSCAD and Node.js user, It's my belief that an approach similar to `npm` would work for this project.  And while package management isn't quite solved problem, virtually every platform shares the same main characteristics:  Version controlled packages served from a central hub, with a web interface, with links back to the project homepages (generally GitHub or GitLab).

I don't think this project should try to reinvent the wheel with regards to decentralization; If anything, centralizing the packages is paramount to achieving the discoverability goal mentioned above.

**Comment by Irev-Dev** [comment]
Thanks @HKalbasi, really well laid out discussion of the problem.

Honestly I'd be okay with **Http import and use** as a stop gap, I don't think broken URLs would actually be that big of a problem since most of the community would probably move to wards a defacto standard of using Github releases anyway and that should make for robust URLs.

But Also like **An alternative module path resolve method** as something that could continue to be built on.

@t-paul mentioned to me https://github.com/entropic-dev/entropic which is supposed to be an agnostic package manager, but it doesn't seem very active these days.

**Comment by fearthecowboy** [comment]
O_O.

This is a place in OpenSCAD that I can contribute. 

I have a lot of experience in package management, and I'm actually working on something right this very moment, which with very little effort could hit most of the important points. With very minor additions to OpenSCAD itself, I think we could hit a very high level of joy.

Step zero is ... finishing the process of actually open-sourcing the current code I have.  I'm building it for my employer, but it's intended to be released and MIT licensed. 

Even if I just hard fork it and tailor it to suit OpenSCAD only, it'll be really fast to put something together. 

I can't say more at the moment, but ... I'm not very far out from being able to do so.

**Comment by t-paul** [comment]
That sounds awesome. I do have some rough ideas what would be nice to have (e.g. ideally not requiring another scripting language to be installed), but there's no fixed plan. So we should be able to find some common direction. This is certainly a feature that would be welcomed by lots of users.

If you want to talk, feel free to drop by our IRC channel [#openscad](https://web.libera.chat/?channel=#openscad) at [Libera.Chat](https://libera.chat/).

**Comment by fearthecowboy** [comment]
Good news; I finally got the signoff to be able to publish the stuff I'm working on from my Employer 😄 

Gimme a couple days and I'll write up something that talks about the approach and how it works.

**Comment by fearthecowboy** [comment]
*Sorry for the delay; I had written out what I wanted to say, and then forgot to save it before closing a screen, and then got real busy this week.*
<hr>

Up Front: I'm on the Embedded/Cross-platform C++ team at Microsoft. Don't let that bother you. 

We've been building a tool for Embedded C++ developers to help acquire tools, sdks, libraries, and other 'artifacts' needed for their embedded development, and then configure the development environment to use them.

Instead of writing a somewhat typical "package manager" that requires repackaging of existing content, curation of large repositories, and some kind of walled garden, I've designed the whole thing to instead take advantage of the heterogeneous nature of the ecosystem and work with everything where it already is.

The tool is called `VCPKG-CE` which is a component of `VCPKG` (a package manager for building C++ libraries) -- but does not have a dependency on `VCPKG`; it can be standalone without issue.

`CE` stands for 'configure-environment' and can be used for entirely different things.  I'll refer to it as just `CE` for now.

**Here's the idea:**

Think of it as a manifest-driven desired state configuration for projects.

Instead of 'packages', we have `artifacts`. `Artifacts` can be any tools, libraries, sdks, etc. The physical artifacts are an archive -- .zip files, .tar.gz/bz2 files,... or even a *git repository*.
More importantly, artifacts are **not** repackaged, rebuilt, rehosted, or modified to be used with the tool.

All we write is a metadata file (a `manifest`) that references the `artifact`s that we want to use. 

Instead of requiring a single centralized registry that requires ongoing effort to curate and maintain, we make a `registry` easy to create. Just make a repo of some manifest files, and generate an index. These can be local directories, or hosted on the web (like a GitHub repository). No service is necesarry at all. 

If you do want a centralized repository, it can be created with a simple github repo, and a couple of github actions to keep the index up-to-date. 

Benefits of `CE`:
  - Cross-platform (Windows/Linux/OSX).  
   `CE` is written in TypeScript and requires node.js to run -- BUT -- don't worry. 
    The script that installs it takes care of that and brings along an isolated copy of node, and doesn't require to you even notice that it's there. You should never need to see it or worry about what version it needs.

  - No admin/root access requires ever. At All. Even the installer. The entire thing is designed to be run with just regular use permissions. 

  - Bootstrapping is super easy. a single 'one-liner' is available for all the shells, and you can run it in on your desktop, in CI/CD, or anywhere you need to use it. No elevated permissions used at all.

  - Works from a blank system. No prerequisites or dependencies that it doesn't manage all by itself.
    *(On Linux IIRC, the assumption is that glibc is used. I probably would need to tweak a couple things for a MUSLC based distro )*

  - Does not make any changes to your system configuration. Does not modify the system PATH/$PATH. 
    Entirely constrained to the shell [`Bash`/`Zsh` (really,any Posix compatible shell should work), `PowerShell`,`Pwsh`, `CMD`] window you are working in.

  - Today, it's a command-line based tool, but we're looking down the road for integration into things like VSCode, VS, etc. 

  - Isolation: Every artifact is installed into a distict folder, and you can have multiple versions of the same artifact installed concurrently without any concern or conflict.
   
  - Projects: a project `manifest` declares the artifacts/versions that a given project needs. When you want to work on that project, you open up your preferred shell and `activate` the project.  
    That will acquire the specific artifacts that project needs (if they aren't already acquired) and configure the shell's environment to use them

    >In C/C++ terms, the `artifact` `manifest` expresses the paths, binaries, include files, environment variable, and other settings that an artifact exposes.

    When the `artifact`s are pulled down, they get unpacked into a (user-global) folder, and we update the environment so that the binaries are on the PATH, and set any other variables that are necessary. 

    `Artifact`s are never dumped into the project folder, they're *referenced* from the (user-global) folder.

  - Restoration is always trivial. Run the bootstrap script and call `activate`.  
    Think something got broken somehwere? Blow away the whole installation folder and re run the bootstrap script and 'activate'  
    No state is difficult to restore at all. 

  - `Artifact Metadata` is incredibly simple to write. A simple file with name/version/description and references to the artifact itself. That's it. 
    You can even specify different conditions that affect what file/settings are used for the artifact. 
    >In C++, this lets you specify a different .zip or .tgz file for a tool depending on platform/architecture/etc, so that 
    and artifact can be use on multiple platforms without changing the project manifest.

    Artifact metadata is in YAML/JSON format. (I prefer YAML simply beacuse it is simpler to edit manually, and doesn't suffer from particularly painful punctuation problems perpetuated purposefully by JSON or XML)

  - Only one data-format. Project Manifests and Artifact Metadata are the same file format. This means that a project can become an artifact trivially. 

**Thoughts:**

`CE` is heavily influeced by NPM/NuGet/venv/etc, but tries to be a lot less complicated.
While it is created for the purpose of managing C++ development environments, it is almost entirely not specific to that whatsoever.

Looking at the way that OpenSCAD supports the `OPENSCADPATH` environment variable, I think that using `CE` should't even require any changes to make this all work. 
Artifacts can be written to specify that they need to be added to the `OPENSCADPATH` environment variable, and `CE` can compose that at activation time.

> **NOTE - BUG**: I had problems with openscad and the `OPENSCADPATH` environment variable. It does not seem to pick up libraries that are in folders that are not in the first entry.  
If I had a an OPENSCADPATH like: `C:\bla\bla\openscad\2021.1.0\libraries;C:\bla\bla\libraries.mcad\1.0.0` it does not find MCAD in the `C:\bla\bla\libraries.mcad\1.0.0` path. If I swap the entries to `C:\bla\bla\libraries.mcad\1.0.0;C:\bla\bla\openscad\2021.1.0\libraries` it does find MCAD, but won't pick up libraries from the other path.

About the only thing that I even see that might be a good idea, is to produce OpenSCAD binaries for Linux/OSX as .tgz files with static-linked/self-contained libraries and that way we could have an artifact that represents OpenSCAD itself, Like you do for Windows as .zip files,
That would make it trivial to have a project just reference OpenSCAD itself as an artifact, making it trivial to get going on a system with zero prerequisites.

**example usage**

Some examples of artifact metadata files for things that exist today:

> `openscad-2001.1.0.yaml` -- OpenSCAD itself **note:** this is an actual working manifest for OpenSCAD. Not a 'mock-up' Works as intended 
``` yaml
info: 
  id: openscad
  version: 2021.1.0
  summary: OpenSCAD is a 3D CAD program for the creation of 3D models.
  description: |
    OpenSCAD is software for creating solid 3D CAD models. It is free software and available for Linux/UNIX, Windows and Mac OS X. Unlike most free software for creating 3D models (such as Blender) it does not focus on the artistic aspects of 3D modelling but instead on the CAD aspects. Thus it might be the application you are looking for when you are planning to create 3D models of machine parts but pretty sure is not what you are looking for when you are more interested in creating computer-animated movies.
    OpenSCAD is not an interactive modeller. Instead it is something like a 3D-compiler that reads in a script file that describes the object and renders the 3D model from this script file. This gives you (the designer) full control over the modelling process and enables you to easily change any step in the modelling process or make designs that are defined by configurable parameters.
    OpenSCAD provides two main modelling techniques: First there is constructive solid geometry (aka CSG) and second there is extrusion of 2D outlines. Autocad DXF files can be used as the data exchange format for such 2D outlines. In addition to 2D paths for extrusion it is also possible to read design parameters from DXF files. Besides DXF files OpenSCAD can read and create 3D models in the STL and OFF file formats.

demands:
  windows and x86: 
    install: 
      unzip: https://files.openscad.org/OpenSCAD-2021.01-x86-32.zip
      strip: 1 # strip off the base directory from inside the zip file.
      sha256: e5ed42fce82b212f21d592aebf2c12c02ddf402163d24cfb736545ab18a51e4a

  windows and x64:
    install: 
      unzip: https://files.openscad.org/OpenSCAD-2021.01-x86-64.zip
      strip: 1 # strip off the base directory from inside the zip file.
      sha256: fb0caabf5bbc89f8f2f80c10b79ae64d697aaff6efd58b2756f5d6270edb7ba7

  windows:  # common to all windows platforms
    settings:
        tools: 
          openscad: openscad.exe # this sets an environment variable that has the full path to 'openscad' 
```

> `libraries/mcad-1.0.0.yaml` -- A standalone MCAD library:

``` yaml
info: 
  id: libraries/mcad
  version: 1.0.0
  summary: OpenSCAD Parametric CAD Library (LGPL 2.1)
  description: |
    This library contains components commonly used in designing and mocking up mechanical designs. It is currently unfinished and you can expect some API changes, however many things are already working.
    This library was created by various authors as named in the individual files' comments. All the files are licensed under the LGPL 2.1 (see http://creativecommons.org/licenses/LGPL/2.1/ or the included file lgpl-2.1.txt), some of them allow distribution under more permissive terms (as described in the files' comments).

install:
  unzip: https://github.com/openscad/MCAD/archive/bd0a7ba3f042bfbced5ca1894b236cea08904e26.zip
  sha256: BD40207753BB5111AC2022DA47BDD0CBA91393018BADEBC8541B8CB1D9F8572A
  transform: s/.*?\//MCAD\//

settings: 
  paths:
    openscadpath: .
```

> Now, if you have a project folder with:

> `environment.yaml`: 
``` yaml
info:
  name: my-little-round-box
  version: 1.0.0

registries:
  - kind: artifact
    location: https://github.com/
    name: openscad
    
requires:
  openscad:openscad: "* 2021.1.0"

```
and
> `sample.scad`
``` scad
use <MCAD/boxes.scad>;

translate([180, 0, 60]) rotate([0, 90, 90]) roundedCube(size = [60, 180, 180], r = 5, sidesonly = true);
```


After that, on a completely blank computer:

``` powershell
iex (iwr -useb aka.ms/install-ce.ps1)

ce activate

openscad.exe ./sample.scad
```

A video of it in action:
https://user-images.githubusercontent.com/133736/142738644-bcdca593-0553-43b3-9571-69dc6edb7108.mp4
